# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.6
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Modules that improve UX sensibly
repo_name: Odoo Usability modules
repo_slug: odoo-usability
travis_apt_packages: []
travis_apt_sources: []
