[project]
name = "odoo-addons-akretion-odoo-usability"
version = "18.0.20260618.0"
dependencies = [
    "odoo-addon-account_bank_reconciliation_summary_xlsx==18.0.*",
    "odoo-addon-account_invoice_update_wizard==18.0.*",
    "odoo-addon-account_reconcile_oca_usability_akretion==18.0.*",
    "odoo-addon-account_usability_akretion==18.0.*",
    "odoo-addon-base_company_extension==18.0.*",
    "odoo-addon-base_dynamic_list==18.0.*",
    "odoo-addon-base_mail_sender_bcc==18.0.*",
    "odoo-addon-base_partner_one2many_phone==18.0.*",
    "odoo-addon-base_partner_ref==18.0.*",
    "odoo-addon-base_profile_akretion==18.0.*",
    "odoo-addon-base_usability_akretion==18.0.*",
    "odoo-addon-commission_simple==18.0.*",
    "odoo-addon-commission_simple_agent==18.0.*",
    "odoo-addon-commission_simple_agent_purchase==18.0.*",
    "odoo-addon-crm_usability_akretion==18.0.*",
    "odoo-addon-eradicate_quick_create==18.0.*",
    "odoo-addon-hr_contract_usability_akretion==18.0.*",
    "odoo-addon-l10n_fr_account_profile_akretion==18.0.*",
    "odoo-addon-link_tracker_usability_akretion==18.0.*",
    "odoo-addon-mail_usability_akretion==18.0.*",
    "odoo-addon-mass_mailing_usability_akretion==18.0.*",
    "odoo-addon-mrp_usability_akretion==18.0.*",
    "odoo-addon-partner_products_shortcut==18.0.*",
    "odoo-addon-partner_tree_default_account==18.0.*",
    "odoo-addon-partner_tree_default_base==18.0.*",
    "odoo-addon-partner_tree_default_contacts==18.0.*",
    "odoo-addon-pos_check_deposit==18.0.*",
    "odoo-addon-pos_product_tree_default==18.0.*",
    "odoo-addon-pos_usability_akretion==18.0.*",
    "odoo-addon-product_category_tax_akretion==18.0.*",
    "odoo-addon-product_detailed_type==18.0.*",
    "odoo-addon-product_detailed_type_stock==18.0.*",
    "odoo-addon-product_manager_group==18.0.*",
    "odoo-addon-product_manager_group_stock==18.0.*",
    "odoo-addon-product_print_zpl_barcode==18.0.*",
    "odoo-addon-product_usability_akretion==18.0.*",
    "odoo-addon-purchase_product_tree_default==18.0.*",
    "odoo-addon-purchase_stock_usability_akretion==18.0.*",
    "odoo-addon-purchase_usability_akretion==18.0.*",
    "odoo-addon-sale_agent==18.0.*",
    "odoo-addon-sale_order_route==18.0.*",
    "odoo-addon-sale_product_tree_default==18.0.*",
    "odoo-addon-sale_quotation_title==18.0.*",
    "odoo-addon-sale_stock_usability_akretion==18.0.*",
    "odoo-addon-sale_usability_akretion==18.0.*",
    "odoo-addon-stock_product_tree_default==18.0.*",
    "odoo-addon-stock_quant_package_move_wizard==18.0.*",
    "odoo-addon-stock_usability_akretion==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
